name: Gateway Conformance Dashboard

on:
  workflow_dispatch:
  push:
    branches:
      - master
  schedule:
    - cron: "0 */1 * * *" # every one hour

concurrency:
  group: "conformance"
  cancel-in-progress: true

defaults:
  run:
    shell: bash

jobs:
  configure:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
     - name: Checkout to repository
       uses: actions/checkout@v3
     - name: Set matrix data
       id: set-matrix
       run: |
        echo "matrix=$(jq -c . < ./src/gateways.json)" >> $GITHUB_OUTPUT
  print:
    runs-on: ubuntu-latest
    needs: configure
    strategy:
      matrix:
          gateway: ${{ fromJson(needs.configure.outputs.matrix) }}
    steps:
     - run: echo ${{ matrix.gateway }}
